import Navbar from "@/components/index.js";
import { Inter } from "next/font/google";
import "./globals.css";


import "react-loading-skeleton/dist/skeleton.css";
import "simplebar-react/dist/simplebar.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen font-sans antialiased grainy`}
      >
        {children}
      </body>
    </html>
  );
}
